### ISSUE TITLE
"%1 is not a valid win32 application" on require after successful compile?

### ISSUE THREAD

**Issue by joeherwig** [EvenAR/node-simconnect#1]
Hi Even,

I'm getting a 

> Error: %1 is not a valid win32 application  ...\node-simconnect\build\Release\node-simconnect.node

at the `require('../../build/Release/node-simconnect');`
after comiling it via `node-gyp configure rebuild --msvs_version=2015 --arch=ia32` when i run `node .\examples\nodejs\example.js`

Did i probably miss anything on installation or build? I'm using the MS c++ 2015 standalone build tools for building the node file. 

`node-gyp configure` shows:
```
<pre>
node-gyp@3.6.2
node@8.2.1 | win32 | x64
C:\Python27\python.exe
[ 'C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
'binding.gyp',
'-f',
'msvs',
'-G',
'msvs_version=2015',
'-I',
'C:\\Users\\me\\GitHub\\node-simconnect\\build\\config.gypi',
'-I',
'C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
'-I',
'C:\\Users\\me\\.node-gyp\\8.2.1\\include\\node\\common.gypi',
'-Dlibrary=shared_library',
'-Dvisibility=default',
'-Dnode_root_dir=C:\\Users\\me\\.node-gyp\\8.2.1',
'-Dnode_gyp_dir=C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
'-Dnode_lib_file=C:\\Users\\me\\.node-gyp\\8.2.1\\<(target_arch)\\node.lib',
'-Dmodule_root_dir=C:\\Users\\me\\GitHub\\node-simconnect',
'-Dnode_engine=v8',
'--depth=.',
'--no-parallel',
'--generator-output',
'C:\\Users\\me\\GitHub\\node-simconnect\\build',
'-Goutput_dir=.' ]</pre>```

Any suggestions?

**Comment by EvenAR** [comment]
Hi! Are you sure you have installed the 32 bit version of node.js? You can find the 32 bit version here: https://nodejs.org/en/download/current/

The reason for using 32 bit is that the FSX SDK only includes 32 bit libraries.. I'm not sure if it's possible to work around this.

**Comment by joeherwig** [comment]
my error...
Since i'm running Node always 64 Bit and have P3D v4 (64 Bit) with 64 Bit Simconnect on my other Host, i forgot to run the 32 Bit versions on this host. (P3V v3) :-)

Thanks a lot. Best regards!
