### ISSUE TITLE
Readme: api vs examples mismatch

### ISSUE THREAD

**Issue by WORMSS** [EvenAR/node-simconnect#16]
Your Readme currently lists the api as 
```ts
open(function, function, function, function)
```
but your example has
```ts
open(string, function, function, function, function)
```
I haven't used the package yet to know which is the correct api, I am just doing the Typescript boilerplate for it, but just noticed the inconsistency.

PS: expect a PR for typescript typings.

**Comment by EvenAR** [comment]
👍 I have updated the readme in the master branch.
