### ISSUE TITLE
Does this work with the new MSFS 2020?

### ISSUE THREAD

**Issue by SafeShows** [EvenAR/node-simconnect#19]
I would like to know if this works with the Microsoft Flight Simulator 2020?

**Comment by Calyhre** [comment]
It does, but I only tried in 64 bits. There is also a few issues I found on the way, see #20, #21 & #22 for example.

**Comment by SafeShows** [comment]
Okay thank you

**Comment by EvenAR** [comment]
The included 32 bit build works too, at least with today's release. (`v1.4.1`)
