### ISSUE TITLE
Module Not Found | Electron v11.2.0

### ISSUE THREAD

**Issue by hiaaryan** [EvenAR/node-simconnect#29]
![image](https://user-images.githubusercontent.com/30364412/107698293-55051980-6cda-11eb-91cc-aae8f2ba85c6.png)

Hello!
I have an electron build for MSFS2020. It builds successfully, I copy the SimConnect.dll to build/Release folder, however it fails to import the module.

Here's what I run for my build
`HOME=~/.electron-gyp node-gyp rebuild --target=11.2.0 --arch=x64 --msvs_version=2019 --dist-url=https://electronjs.org/headers`

Using node x64.

I am using the refactor branch.

This command works perfectly:
`node examples/nodejs/example.js`

**Comment by zeykafx** [comment]
how did you fix this?
