### ISSUE TITLE
ETA on the refactor branch being done?

### ISSUE THREAD

**Issue by westlakem** [EvenAR/node-simconnect#33]
It's been about a year since the start of the refactor... Do you have a timeframe on when that will be complete?  About to start a new project.

**Comment by zeykafx** [comment]
I can't even get it to work in my react electron app

**Comment by westlakem** [comment]
Bump

**Comment by westlakem** [comment]
bump again

**Comment by EvenAR** [comment]
@westlakem sorry, this branch will probably be deleted. I have started on yet another refactor which will be a more complete client. The good thing about this is that it talks directly to SimConnect natively through pipes or TCP, and doesn't rely on the official SDK library. It will support all of the functionality that the old `node-simconnect` does, but right now the API is quite different. It's possible to try it already, but expect breaking changes to come. `npm install node-simconnect@alpha` ([refactor-native](https://github.com/EvenAR/node-simconnect/tree/refactor-native) branch)

**Comment by westlakem** [comment]
Hey @EvenAR 
Thanks for the response but after almost 2 years with no communication or progress I moved over to using FSUIPC & FSUIPC API libraries, as I was running into issues not being able to use the latest 3ish versions of electron with this package.  Wish you the best of luck.

**Comment by EvenAR** [comment]
Totally understandable @westlakem. Thanks!

Closing this issue as v3 is now the official version.
