### ISSUE TITLE
Issues when sim not running or shut down normally

### ISSUE THREAD

**Issue by BarryCarlyon** [EvenAR/node-simconnect#44]
NodeSimconnect: v3.0.1
Platform: Windows
Node: v18.9.0
Electron: v20.2.0
Simulator: Technically none but MSFS.

If I do not start the simulator 
if I run the following code:

```javascript
    try {
        console.log('Trying simconnect');
        // simulator time
        //import { open, Protocol } from 'node-simconnect';
        let simconnect = require('node-simconnect');

        let { SimConnectConstants, SimConnectPeriod, SimObjectType } = simconnect;

        console.log('Required simconnect');

        console.log('opening');
        simconnect.open('FlightSimTrack', simconnect.Protocol.FSX_SP2)
            .then(({ recvOpen, handle }) => {
                handle.on('quit', function () {
                    console.log('Simulator quit');
                });

                handle.subscribeToSystemEvent(1, 'Pause');
                handle.subscribeToSystemEvent(2, 'Paused');
                handle.subscribeToSystemEvent(3, 'FlightLoaded');
                handle.subscribeToSystemEvent(4, 'FlightSaved');
                handle.subscribeToSystemEvent(5, 'FlightPlanActivated');
                handle.subscribeToSystemEvent(6, 'FlightPlanDeactivated');
                handle.subscribeToSystemEvent(7, 'View');

                handle.on('event', function (recvEvent) {
                    console.log('event', recvEvent);
                    switch (recvEvent.clientEventId) {
                        case 1:
                        case 2:
                            console.log(recvEvent.data === 1 ? 'Sim paused' : 'Sim unpaused');
                            break;
                        case 3:
                        case 4:
                            console.log('Flight Loaded/Saved');
                            break;
                        case 5:
                        case 6:
                            console.log('Flight Plan');
                            break;
                        case 7:
                            console.log('view');
                            break;
                    }
                });
            })
            .catch(err => {
                console.log('Sim Connection Failed', err);
            });
    } catch (e) {
        console.log('Sim Connection Bad Failed', e);
    }
```

The result is

![image](https://user-images.githubusercontent.com/20999/192166611-314f19f8-4871-47f6-bc58-f5762baf78e8.png)

And ` console.log('Sim Connection Bad Failed', e);` doesn't trigger.

or if caught by BugSnag

```
[bugsnag] Event not sent due to releaseStage/enabledReleaseStages configuration
[bugsnag] Uncaught exception, the process will now terminateÔÇª
Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:64249)
    at internalConnect (node:net:953:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1097:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8)
```
And the electron app CTD's

I just can't "catch" the error.

In a similar vein on normal sim shutdown: where I have a timer function calling `requestDataOnSimObjectType` somewhere. the following occurs:

```
Simulator quit
[bugsnag] Event not sent due to releaseStage/enabledReleaseStages configuration
[bugsnag] Uncaught exception, the process will now terminateÔÇª
Error: read EPIPE
    at Pipe.onStreamRead (node:internal/stream_base_commons:217:20)
```

And the electron app CTD's

In my testing my simconnect app has caused the sim to CTD and the app doesn't error/CTD (but doesn't reconnect and pick back up, but thats handle just being weird all over the place. but I need to test 

However in a test just now that caused a CTD of the sim

```
event RecvEvent { groupID: -1, clientEventId: 7, data: 0 }
view
states { twitch: 1, sim: 0, discord: 0 }
Connecting to twitch socket
Them
Connected to socket
states { twitch: 2, sim: 0, discord: 0 }
Them
Them
Them
Them
[bugsnag] Event not sent due to releaseStage/enabledReleaseStages configuration
[bugsnag] Uncaught exception, the process will now terminateÔÇª
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (node:net:487:14)
    at SimConnectSocket._write (E:\Work\FlightSim\electron\node_modules\node-simconnect\dist\SimConnectSocket.js:110:22)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at SimConnectConnection.sendPacket (E:\Work\FlightSim\electron\node_modules\node-simconnect\dist\SimConnectConnection.js:156:27)
    at SimConnectConnection.requestDataOnSimObjectType (E:\Work\FlightSim\electron\node_modules\node-simconnect\dist\SimConnectConnection.js:226:14)
    at them (E:\Work\FlightSim\electron\app\modules\app.js:188:16)
    at Timeout._onTimeout (E:\Work\FlightSim\electron\app\modules\app.js:195:13)
PS E:\Work\FlightSim\electron>
```

And the app CTD's to desktop with an uncatchable.

I'm off to try and add a process uncuaght to prevent my app ctd's. but it's odd my try/catch isn't catching (or the code examples catch in the then/catch loop), and it's backing up to a uncuaght

Additional notes:

This is similar to #25

**Comment by EvenAR** [comment]
Thanks for the detailed description! I will publish a fix for the non-catchable EADDRNOTAVAIL error soon with a sample of some reconnect logic  (#45).

Regarding the "read EPIPE"-error and the CTD; one workaround might be to stop your timer as soon as you receive a `"quit"` or `"close"` event. I'm a bit unsure how it would make sense to handle this in `node-simconnect`, and if it should be `node-simconnect`'s responsibility at all 🤔Do you know how the  

For the sim CTD-issue; do you have a short sample code I can use to reproduce this?

**Comment by BarryCarlyon** [comment]
> For the sim CTD-issue; do you have a short sample code I can use to reproduce this?

Add to your data definition a `TITLE` and use the wrong data type for it.
Then request data on the player or other sim objects. (A sim bug I need to go report, but it's a reliable "crash the sim")

I'll grab some code later today. But thats what I'm doing.

> Regarding the "read EPIPE"-error and the CTD; one workaround might be to stop your timer as soon as you receive a "quit" or "close" event. I'm a bit unsure how it would make sense to handle this in node-simconnect internally, and if it should be node-simconnect's responsibility at all 🤔

Yeah thats my plan.

But there are cases where `quit` doesn't fire (like the CTD issue). I'll hook onto `close` (wasn't in the docs didn't know was a thing so I'll give that a while)

This version (like the old version) I sandbox my simconnect code in a seperate process so when the seperate process dies for whatever reason (sim not being avaiable the primary one) the master process catches and restarts the process anyway.

Bulk of my work is migrating the old app to the new node module. Then I can schnanigan other things

**Comment by EvenAR** [comment]
> Add to your data definition a `TITLE` and use the wrong data type for it.
> Then request data on the player or other sim objects. (A sim bug I need to go report, but it's a reliable "crash the sim")

Thanks. I tested this now and the CTD did trigger the `close` event. So I guess you can use that like you use `quit`. Note that a regular `quit` will always be followed by a `close`-event, so you need to check if `quit` has already been called when you get the `close` event, so you don't handle it twice (see the `reconnect.ts` sample).

**Comment by BarryCarlyon** [comment]
I'll give it a whirl.

And yeah double events are fine I usually have code setup for that just in case

**Comment by BarryCarlyon** [comment]
Finally Tested. 

Can confirm looks good under 3.0.4 to me!
