### ISSUE TITLE
Why GPL instead of LGPL?

### ISSUE THREAD

**Issue by RobsonMi** [EvenAR/node-simconnect#48]
Hi, just noticed license change from MIT to GPL 3 which is very unfortunate as GPL 3 basically prevents usage in any proprietary projects that can't go open source.

Can't the LGPL be used instead as it is on jsimconnect (https://github.com/mharj/jsimconnect/blob/master/LICENSE)? This would still force any changes and developments of the lib to be open source while allowing any proprietary software to use it as is.

Hope this can be changed ;)

**Comment by EvenAR** [comment]
Fixed in  edae692f6354d772446906aed3193d02ca5f6d62
