### ISSUE TITLE
Need example on how to write simulation variables

### ISSUE THREAD

**Issue by MatthausNawan** [EvenAR/node-simconnect#61]
Help, I need a Example how i can set a fuel tank quantity. EG "FUEL TANK CENTER LEVEL"

**Comment by MatthausNawan** [comment]
I 've trying to set some SIMVAR but i dont find a documentation how to.

```
 open('FUEL_SYSTEM', Protocol.FSX_SP2).then(({ recvOpen, handle }) => {

        console.log('Connected:', recvOpen);

        handle.addToDataDefinition(DefinitionID.DEF_FUEL, "CENTER TANK QUANTITY", 'percent', SimConnectDataType.INT32, 0);

        handle.setDataOnSimObject(DefinitionID.DEF_FUEL, SimConnectConstants.OBJECT_ID_USER,)
        )
```

I need a example for setData for any SIMVARS for LIGHTS, FUEL,AP

**Comment by EvenAR** [comment]
I'm not currently able to test this myself, but I believe something like this should work:

```js
const data = new RawBuffer();
data.writeInt(50); // 50%

handle.setDataOnSimObject(
    DefinitionID.DEF_FUEL,
    SimConnectConstants.OBJECT_ID_USER,
    { buffer: data, arrayCount: 1, tagged: false }
)
```

**Comment by sadu** [comment]
```js
const data = new RawBuffer();
data.writeInt(50); // 50%
```

I can't initialize this RawBuffer without a constructor parameter. Is there any reference in source code where the buffer size(which is the parameter I am guessing) is not being set initially?

Do you have any instances in the lib or any project that utilize node-simconnect to write a simvar?

**Comment by EvenAR** [comment]
@sadu Ah, yes you need to provide a size. It doesn’t matter what it is as long as it makes enough space for the data you will send. It’s used here: https://github.com/EvenAR/node-simconnect/blob/e181433e4038bf10cc6fcfd1053868295abf7978/src/SimConnectConnection.ts#L168

**Comment by EvenAR** [comment]
@MatthausNawan, I have added a sample: https://github.com/EvenAR/node-simconnect/blob/9cc7185a7a7fc9be1a53c95c274390efd1d04636/samples/typescript/simulationVariablesWrite.ts
Hope this is helpful.

**Comment by MatthausNawan** [comment]
Thank you fot that
