### ISSUE TITLE
Bytebuffer format on electron.

### ISSUE THREAD

**Issue by joaogn** [EvenAR/node-simconnect#64]
I'm trying to use this excellent lib on the electron.  But I have a weird bug.

I'm receiving this error on electron;

<img width="493" alt="Screenshot 2023-02-11 at 13 42 44" src="https://user-images.githubusercontent.com/10895903/218270067-0c84410b-abec-4550-adc6-4c63fec42dbb.png">

So I started to investigate and I found the main point of the error, basically, it looked like running two different versions of bytebuffer.

- on electron
![Screenshot 2023-02-11 at 13 39 32](https://user-images.githubusercontent.com/10895903/218270175-65024ff3-d41a-4839-8d61-99e2491e0d08.png)

- on node
![Screenshot 2023-02-11 at 13 39 47](https://user-images.githubusercontent.com/10895903/218270206-515c0982-c866-4199-bf1d-013eabe40d33.png)

 I tried to investigate the package-lock but I don't find anything relevant.

Do you have any idea what could be?

**Comment by joaogn** [comment]
Okay I find the problem.

![Screenshot 2023-02-11 at 13 58 09](https://user-images.githubusercontent.com/10895903/218270767-060f738b-8184-4709-ba01-cf8fc6364a4b.png)

I will check if I can find a solution.

**Comment by joaogn** [comment]
I force to use directly the node version to work.  If you think this is an elegant solution I can do a PR.

![Screenshot 2023-02-11 at 14 09 23](https://user-images.githubusercontent.com/10895903/218271270-21e4b8e7-93f7-46c5-98e2-f5ba02928315.png)

**Comment by EvenAR** [comment]
Hi! I think this only will be an issue when using node-simconnect from the renderer process. In my Electron application I use the main process for sim interaction, and IPC for data transfer between the main and renderer process. That's the most elegant solution I know of at the moment.

**Comment by joaogn** [comment]
Weird, I'm using in the main too, and using IPC.  Maybe is anything in my electron setup, I will check.  Thx.

**Comment by EvenAR** [comment]
Did you find a solution, @joaogn ?

**Comment by joaogn** [comment]
Sorry by the late reply,  I find a workaround, I'm using "electron-vite" to build my app, so I suppose should it that it recognize as web.  Bassicaly I'm using 'vite-plugin-static-copy' to copy the 'bytebuffer-node.js' to the 'bytebuffer.js' in the build process, So this solved my problem.
