### ISSUE TITLE
Add some code to the README.md to show how to get and set values?

### ISSUE THREAD

**Issue by Pomax** [EvenAR/node-simconnect#65]
Unlike python-simconnect, there does not appear to be anything in the readme that shows how to actually get and set simvars. Can the example be updated to show how to work with those?

**Comment by joaogn** [comment]
There are very good examples in the folder samples.

**Comment by Pomax** [comment]
Tha samples folder seems to suggest people need to first implement the entire MSFS ("KittyHawk") API themselves, though. Does every dev really need to do this for themselves instead of just importing a getter/setter class for the MSFS simvars?

**Comment by Pomax** [comment]
Cheers. That's unfortunate. I was hoping someone'd written a Node library to use SimConnect in a "general JS API" way, rather than a JS emulation of a C++ SDK =)

**Comment by Pomax** [comment]
That said, given that I'm getting kinda few up with Python's absolute nonsense threading model just to get a simple setTimeout going, I might just wget the MSFS docs, and create the "proper JS" API on top of this myself. Then rewrite my article from "Flying planes with Python and JavaScript" to "Flying planes with JavaScript".

**Comment by EvenAR** [comment]
Adding another abstraction level with functions for all available simulation variables would be a quite comprehensive project in itself, I imagine. node-simconnect is supposed to provide only the bare minimums required to interact with SimConnect without having to write dll-bindings or using a .net-application as a proxy. If someone can use node-simconnect as a foundation for developing a more modern library on top of it, they are very welcome to do so! 😃 

Since the readme is quire long already, I think it's better to leave most of the samples outside of it. Did you find all you needed in the samples folder?

**Comment by Pomax** [comment]
Created a repo where I'll be plodding along for a bit while I implement the entirety of the MSFS SimConnect simvar list... which is a chore, absolutely, but also not _too_ hard with the Hades OST playing in the background.

https://github.com/Pomax/msfs-simconnect-api-wrapper/commit/69efcd9899fff0b83ba8af34e3300cb86d41d04c

**Comment by Pomax** [comment]
And done. https://github.com/Pomax/msfs-simconnect-api-wrapper now supports all simvars, all system events, and allows triggering of all simevents. I'll spend the weekend porting all my python code over, which should hopefully reveal any errors I made with node-simconnect calls, but barring those, this might be a "less powerful, but easy to use" JS package for talking to MSFS

(because of course the more options folks have to write some code against MSFS, the bigger the community gets! =D)

**Comment by EvenAR** [comment]
That was quick! Your project looks awesome! I will add a link to it in the README once it’s on npm 😃

**Comment by Pomax** [comment]
Yeah, it turns out that the MSFS docs are actually really well structured, so you can just copy-paste from the website and have a list that you can relatively easily (with _some_ massaging of course) regex into perfectly servicible JS =D

Just published the project to NPM (with the classic three immediate "oh shit I forgot to..." minor/patch updates!) so it should be live over on https://www.npmjs.com/package/msfs-simconnect-api-wrapper

**Comment by Pomax** [comment]
Hm, looks like I'm doing something wrong wrt data request, so I may need to dig through the docs - right now after 1000 get/set, the SDK throws a `SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS` at me, so even though I'm calling andle.clearDataDefinition(REQUEST_ID), that's not actually clearing what I'm thinking it would clear... =/

**Comment by Pomax** [comment]
never mind, false alarm. Well, "ish": I had written the `get()` calls to clean up after themselves, but forgot to do the same for the `set` calls, and since the code I'm testing is an autopilot that's setting several trim and control values per second, it ran out of unallocated IDs _pretty_ quickly. Fixed it, pushed up a new version of the library (v1.1.8), and I've had it running a flight set to JS-based autopilot for about 10 minutes now without getting any exceptions.

**Comment by joaogn** [comment]
Good call @Pomax .
