### ISSUE TITLE
add .once and .off to SimConnectConnection?

### ISSUE THREAD

**Issue by Pomax** [EvenAR/node-simconnect#66]
Currently the SimConnectConnection explicitly supports [.on](https://github.com/EvenAR/node-simconnect/blob/master/src/SimConnectConnection.ts#L180-L185) and [.emit](https://github.com/EvenAR/node-simconnect/blob/master/src/SimConnectConnection.ts#L187-L192), but to prevent "dead" event handlers from hanging around it would be good to also add wrappers for the [.off](https://nodejs.org/api/events.html#emitteroffeventname-listener) and maybe [.once](https://nodejs.org/api/events.html#emitteronceeventname-listener) EventEmitter functions.

They technically work right now, but it might be nicer to have the code make that explicit?

**Comment by Pomax** [comment]
(not sure if `once` is truly useful, but without `off` to clean up one-time event listeners, running a bunch of retrievals with `SimConnectPeriod.ONCE` will made Node throw a `MaxListenersExceededWarning` after a while)

**Comment by EvenAR** [comment]
Good point, thanks for the suggestion. I have added this in v3.4.0 :)
