### ISSUE TITLE
Having some issues with `unSubscribeToFacilitiesEx1`

### ISSUE THREAD

**Issue by Pomax** [EvenAR/node-simconnect#72]
I'm using the (idiotically named, thanks MS!) node-simconnect equivalent of the `SimConnect_SubscribeToFacilities_EX1` call, and can successfully register for "nearby" airport updates, but if I want to do this as a one-time affair, unsubscribing after the initial response, using the equivalent unsubscribe function, SimConnect throws up an exception. Any idea what I'm doing wrong here?

```js
const SIMCONNECT_FACILITY_LIST_TYPE_AIRPORT = 0;
const type = SIMCONNECT_FACILITY_LIST_TYPE_AIRPORT;
const NEW_EVENT_ID = 1;
const OLD_EVENT_ID = -1;
  
handle.on("airportList", (recvAirportList) => {
  console.log(recvAirportList);
  // we got our data, unsubscribe again, with both "new" and "old" set to unsubscribe:
  const packetId = handle.unSubscribeToFacilitiesEx1(type, true, true);
  // this will cause a simconnect exception, with the `sendId` number as the packet we just sent
  console.log(`unsubscribe sendId: ${packetId}`);
});

handle.subscribeToFacilitiesEx1(type, NEW_EVENT_ID, OLD_EVENT_ID);
```

Running this with a plane sitting at NTMN, I get the following output:

```
RecvAirportList {
  requestID: 1,
  arraySize: 4,
  entryNumber: 0,
  outOf: 1,
  aiports: [
    FacilityAirport {
      icao: 'NTMU',
      latitude: -8.936111256480217,
      longitude: -139.5550002157688,
      altitude: 45.415000915527344
    },
    FacilityAirport {
      icao: 'NTMD',
      latitude: -8.793333247303963,
      longitude: -140.2230553328991,
      altitude: 64.00800323486328
    },
    FacilityAirport {
      icao: 'NTMN',
      latitude: -9.768055714666843,
      longitude: -139.01111125946045,
      altitude: 453.8470153808594
    },
    FacilityAirport {
      icao: 'NTMP',
      latitude: -9.350555464625359,
      longitude: -140.07805556058884,
      altitude: 22.860000610351562
    }
  ]
}
unsubscribe sendId: 4
RecvException { exception: 1, sendId: 4, index: 1 }
```

Looking at the code for this function in https://github.com/EvenAR/node-simconnect/blob/master/src/SimConnectConnection.ts#L1289-L1301 it looks like there's a magic number `0x48` for indicating that this is an unsubscribe, is that the correct number? Is there a list in the SimConnect docs to verify this is the correct number?

**Comment by EvenAR** [comment]
I'm quite sure I tested this function myself without getting an exception. Just a shot in the dark - I see you are trying to unsubscribe both "old" and "new" facilities when only subscribing to "new" ones. Perhaps that causes the exception? 🤔 

The magic number indicates which SimConnect-function it is. This was found by inspecting the packets from the official SDK and is not documented anywhere as far as I know.

**Comment by Pomax** [comment]
Definitely worth testing! Unfortunately, it looks like it's the same RecvException when sending `true, false` in order to only unsubscribe from the "new" notification.

**Comment by Pomax** [comment]
A bit of further testing: if I subscribe using positive event ids for both new and old, rather than setting old to -1, the unsubscribe _does_ work.

**Comment by Pomax** [comment]
On a sidenote, I've filed https://github.com/EvenAR/node-simconnect/pull/74 to fix a typo in the code, where the airport list was called "aiports" with its first "r" missing.

**Comment by Pomax** [comment]
Hm, looks like there's some more problems here: subscribing to both the full facilities list and the "near" list, using this:
```js
const TYPE = SIMCONNECT_FACILITY_LIST_TYPE_AIRPORT;
const ALL = this.nextId();
const IN_RANGE = this.nextId();
const OUT_OF_RANGE = this.nextId();

const a = handle.subscribeToFacilities(TYPE, ALL);
const b = handle.subscribeToFacilitiesEx1(TYPE, IN_RANGE, OUT_OF_RANGE);
console.log(`subscriptions: ${a}, ${b}`);
```

results in an "already subscribed" error for the ex1 subscription. Although of course at this point it's entirely possible that SimConnect itself has bugs around this...

```
subscriptions: 3, 4
RecvException { exception: 26, sendId: 4, index: 1 }
```

**Comment by EvenAR** [comment]
There was indeed a problem with my code in `unSubscribeToFacilitiesEx1`. I will make a new release with the fix. You will still get an exception if the bools doesn't match what you have subscribed to though. This seem to be the case for the official `SimConnect_UnsubscribeToFacilities_EX1` too.

Btw, I also tested your last code in the official SDK and got the same exception.

**Comment by Pomax** [comment]
Looks like it, thanks! I'll see if I can't file that exception over on the new simconnect "forum".

**Comment by Pomax** [comment]
oh my goodness, okay so confession time: I looked at those two lines and went "hm, what if I use int32 instead of string?" then that didn't work, I tried "writeInt" thinking it was int8 (looking at it again, it's just an alias for int32... no idea why I didn't spot that before =_=), and then that didn't work and I figured that probably wasn't it.

**Comment by EvenAR** [comment]
Closing as the original issues were solved :)
