### ISSUE TITLE
node-simconnect Does not compile against the latest NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by ghost** [EvenAR/node-simconnect#8]
Hey!

It seems as though the latest node-simconnect (canary) version doesn't compile against the latest NODE_MODULE_VERSION, or any past v72. This is problematic as it will not work with any recent version of Electron or Node. 

Compiling with electron-rebuild gives the same errors.

Here is a pastebin of the log (at the bottom is what happens when I try to run the application):
https://pastebin.com/zJ0y7fw4

**Comment by flightTLV** [comment]
check #6 
solved if you use the "upgrades"  branch

**Comment by EvenAR** [comment]
I'm closing this as the new version works natively with Electron (no custom build needed).
