### ISSUE TITLE
Not a real issue, just a heck of a lot of appreciation.

### ISSUE THREAD

**Issue by Pomax** [EvenAR/node-simconnect#80]
Hey @EvenAR, just wanted to say thank you again, your project allowed me to play around with MSFS so much more than I would have even imagined possible, culminating in this: https://www.youtube.com/watch?v=0aV6WtY6zJE

(though the "real" culmination is probably this ~35k work tutorial that explains how the plane in the video's doing all the things it's doing ;)

But yeah, that's a fully pure JS autopilot _with auto-takeoff_ ***and auto-landing***.

I have no idea how I would have ever gotten to this if it weren't for node-simconnect. Do you have a donation link or patreon or something? Because yeah "thanks are nice" but you know what's even nicer? Money. And I have a donation to make =)

**Comment by EvenAR** [comment]
Hi @Pomax! Thanks a lot for your kind words! That autopilot project is truly impressive! 🤩

Regarding your generous donation offer, I have just set up a GitHub Sponsors account in response to your request. So, if you still feel like contributing, you can find the option on my Github profile. But please know that your support and kind words are already more than enough. The biggest reward for me is knowing that my work has been helpful to you and the flight sim community!

If you ever need any further assistance or have more to share, feel free to reach out. Keep up the amazing work, and happy flying!

**Comment by EvenAR** [comment]
Thank you so much, @Pomax! Your support really helps on my motivation to keep this library updated (the new `requestJetwayData()` will be available [soon](https://github.com/EvenAR/node-simconnect/pull/82) 😄 ).

Looking forward to checking out your tutorial!
